// DispIDs.h: Defines a DISPID for each COM property and method we're providing.

// IExplorerListView
// properties
#define DISPID_EXLVW_ABSOLUTEBKIMAGEPOSITION						1
#define DISPID_EXLVW_ALLOWHEADERDRAGDROP								2
#define DISPID_EXLVW_ALLOWLABELEDITING									3
#define DISPID_EXLVW_ALWAYSSHOWSELECTION								4
#define DISPID_EXLVW_ANCHORITEM													5
#define DISPID_EXLVW_APPEARANCE													6
#define DISPID_EXLVW_AUTOARRANGEITEMS										7
#define DISPID_EXLVW_BACKCOLOR													8
#define DISPID_EXLVW_BKIMAGE														9
#define DISPID_EXLVW_BKIMAGEPOSITIONX										10
#define DISPID_EXLVW_BKIMAGEPOSITIONY										11
#define DISPID_EXLVW_BKIMAGESTYLE												12
#define DISPID_EXLVW_BLENDSELECTIONLASSO								13
#define DISPID_EXLVW_BORDERSELECT												14
#define DISPID_EXLVW_BORDERSTYLE												15
#define DISPID_EXLVW_CALLBACKMASK												16
#define DISPID_EXLVW_CARETITEM													DISPID_VALUE
#define DISPID_EXLVW_CLICKABLECOLUMNHEADERS							17
#define DISPID_EXLVW_COLUMNS														18
#define DISPID_EXLVW_COLUMNWIDTH												19
#define DISPID_EXLVW_DISABLEDEVENTS											20
#define DISPID_EXLVW_DONTREDRAW													21
#define DISPID_EXLVW_DRAGGEDCOLUMN											22
#define DISPID_EXLVW_DRAGGEDITEMS												23
#define DISPID_EXLVW_DRAGSCROLLTIMEBASE									24
#define DISPID_EXLVW_DROPHILITEDITEM										25
#define DISPID_EXLVW_EDITBACKCOLOR											26
#define DISPID_EXLVW_EDITFORECOLOR											27
#define DISPID_EXLVW_EDITHOVERTIME											28
#define DISPID_EXLVW_EDITIMEMODE												29
#define DISPID_EXLVW_EDITTEXT														30
#define DISPID_EXLVW_EMPTYMARKUPTEXT										31
#define DISPID_EXLVW_ENABLED														DISPID_ENABLED
#define DISPID_EXLVW_FILTERCHANGEDTIMEOUT								32
#define DISPID_EXLVW_FIRSTVISIBLEITEM										33
#define DISPID_EXLVW_FONT																34
#define DISPID_EXLVW_FORECOLOR													35
#define DISPID_EXLVW_FULLROWSELECT											36
#define DISPID_EXLVW_GRIDLINES													37
#define DISPID_EXLVW_GROUPFOOTERFORECOLOR								38
#define DISPID_EXLVW_GROUPHEADERFORECOLOR								39
#define DISPID_EXLVW_GROUPMARGINBOTTOM									40
#define DISPID_EXLVW_GROUPMARGINLEFT										41
#define DISPID_EXLVW_GROUPMARGINRIGHT										42
#define DISPID_EXLVW_GROUPMARGINTOP											43
#define DISPID_EXLVW_GROUPS															44
#define DISPID_EXLVW_GROUPSORTORDER											45
#define DISPID_EXLVW_HDRAGIMAGELIST											46
#define DISPID_EXLVW_HEADERFULLDRAGGING									47
#define DISPID_EXLVW_HEADERHOTTRACKING									48
#define DISPID_EXLVW_HEADERHOVERTIME										49
#define DISPID_EXLVW_HIDELABELS													50
#define DISPID_EXLVW_HIMAGELIST													51
#define DISPID_EXLVW_HOTFORECOLOR												52
#define DISPID_EXLVW_HOTITEM														53
#define DISPID_EXLVW_HOTMOUSEICON												54
#define DISPID_EXLVW_HOTMOUSEPOINTER										55
#define DISPID_EXLVW_HOTTRACKING												56
#define DISPID_EXLVW_HOTTRACKINGHOVERTIME								57
#define DISPID_EXLVW_HOVERTIME													58
#define DISPID_EXLVW_HWND																59
#define DISPID_EXLVW_HWNDEDIT														60
#define DISPID_EXLVW_HWNDHEADER													61
#define DISPID_EXLVW_HWNDTOOLTIP												62
#define DISPID_EXLVW_IMEMODE														63
#define DISPID_EXLVW_INCREMENTALSEARCHSTRING						64
#define DISPID_EXLVW_INSERTMARKCOLOR										65
#define DISPID_EXLVW_ITEMACTIVATIONMODE									66
#define DISPID_EXLVW_ITEMALIGNMENT											67
#define DISPID_EXLVW_ITEMBOUNDINGBOXDEFINITION					68
#define DISPID_EXLVW_ITEMHEIGHT													69
#define DISPID_EXLVW_LABELWRAP													70
#define DISPID_EXLVW_LISTITEMS													71
#define DISPID_EXLVW_MOUSEICON													72
#define DISPID_EXLVW_MOUSEPOINTER												73
#define DISPID_EXLVW_MULTISELECT												74
#define DISPID_EXLVW_OUTLINECOLOR												75
#define DISPID_EXLVW_OWNERDRAWN													76
#define DISPID_EXLVW_PROCESSCONTEXTMENUKEYS							77
#define DISPID_EXLVW_REGIONAL														78
#define DISPID_EXLVW_REGISTERFOROLEDRAGDROP							79
#define DISPID_EXLVW_RIGHTTOLEFT												80
#define DISPID_EXLVW_SCROLLBARS													81
#define DISPID_EXLVW_SELECTEDCOLUMN											82
#define DISPID_EXLVW_SHOWDRAGIMAGE											83
#define DISPID_EXLVW_SHOWFILTERBAR											84
#define DISPID_EXLVW_SHOWGROUPS													85
#define DISPID_EXLVW_SHOWSTATEIMAGES										86
#define DISPID_EXLVW_SHOWSUBITEMIMAGES									87
#define DISPID_EXLVW_SIMPLESELECT												88
#define DISPID_EXLVW_SINGLEROW													89
#define DISPID_EXLVW_SNAPTOGRID													90
#define DISPID_EXLVW_SORTORDER													91
#define DISPID_EXLVW_SUPPORTOLEDRAGIMAGES								92
#define DISPID_EXLVW_TEXTBACKCOLOR											93
#define DISPID_EXLVW_TILEVIEWITEMLINES									94
#define DISPID_EXLVW_TILEVIEWLABELMARGINBOTTOM					95
#define DISPID_EXLVW_TILEVIEWLABELMARGINLEFT						96
#define DISPID_EXLVW_TILEVIEWLABELMARGINRIGHT						97
#define DISPID_EXLVW_TILEVIEWLABELMARGINTOP							98
#define DISPID_EXLVW_TOOLTIPS														99
#define DISPID_EXLVW_UNDERLINEDITEMS										100
#define DISPID_EXLVW_USESYSTEMFONT											101
#define DISPID_EXLVW_USEWORKAREAS												102
#define DISPID_EXLVW_VERSION														103
#define DISPID_EXLVW_VIEW																104
#define DISPID_EXLVW_VIRTUALITEMCOUNT										105
#define DISPID_EXLVW_VIRTUALMODE												106
#define DISPID_EXLVW_WORKAREAS													107
#define DISPID_EXLVW_AUTOSIZECOLUMNS										139
#define DISPID_EXLVW_BACKGROUNDDRAWMODE									140
#define DISPID_EXLVW_CARETCOLUMN												141
#define DISPID_EXLVW_CARETGROUP													142
#define DISPID_EXLVW_CHECKITEMONSELECT									143
#define DISPID_EXLVW_COLUMNHEADERVISIBILITY							144
#define DISPID_EXLVW_DRAWIMAGESASYNCHRONOUSLY						145
#define DISPID_EXLVW_EMPTYMARKUPTEXTALIGNMENT						146
#define DISPID_EXLVW_JUSTIFYICONCOLUMNS									147
#define DISPID_EXLVW_RESIZABLECOLUMNS										148
#define DISPID_EXLVW_SHOWHEADERCHEVRON									149
#define DISPID_EXLVW_SHOWHEADERSTATEIMAGES							150
#define DISPID_EXLVW_TILEVIEWTILEHEIGHT									151
#define DISPID_EXLVW_TILEVIEWTILEWIDTH									152
#define DISPID_EXLVW_USEMINCOLUMNWIDTHS									153
#define DISPID_EXLVW_CARETFOOTERITEM										156
#define DISPID_EXLVW_FOOTERINTROTEXT										157
#define DISPID_EXLVW_FOOTERITEMS												158
#define DISPID_EXLVW_HEADEROLEDRAGIMAGESTYLE						159
#define DISPID_EXLVW_INCLUDEHEADERINTABORDER						160
#define DISPID_EXLVW_MINITEMROWSVISIBLEINGROUPS					161
#define DISPID_EXLVW_OLEDRAGIMAGESTYLE									162
#define DISPID_EXLVW_SELECTEDCOLUMNBACKCOLOR						163
#define DISPID_EXLVW_TILEVIEWSUBITEMFORECOLOR						164
#define DISPID_EXLVW_GROUPLOCALE												168
#define DISPID_EXLVW_GROUPTEXTPARSINGFLAGS							169
// fingerprint
#define DISPID_EXLVW_APPID															500
#define DISPID_EXLVW_APPNAME														501
#define DISPID_EXLVW_APPSHORTNAME												502
#define DISPID_EXLVW_BUILD															503
#define DISPID_EXLVW_CHARSET														504
#define DISPID_EXLVW_ISRELEASE													505
#define DISPID_EXLVW_PROGRAMMER													506
#define DISPID_EXLVW_TESTER															507
// methods
#define DISPID_EXLVW_ABOUT															DISPID_ABOUTBOX
#define DISPID_EXLVW_APPROXIMATEVIEWRECTANGLE						108
#define DISPID_EXLVW_ARRANGEITEMS												109
#define DISPID_EXLVW_BEGINDRAG													110
#define DISPID_EXLVW_COUNTVISIBLE												111
#define DISPID_EXLVW_CREATEITEMCONTAINER								112
#define DISPID_EXLVW_ENDDRAG														113
#define DISPID_EXLVW_ENDLABELEDIT												114
#define DISPID_EXLVW_FINDITEM														115
#define DISPID_EXLVW_GETCLOSESTINSERTMARKPOSITION				116
#define DISPID_EXLVW_GETICONSPACING											117
#define DISPID_EXLVW_GETINSERTMARKPOSITION							118
#define DISPID_EXLVW_GETINSERTMARKRECTANGLE							119
#define DISPID_EXLVW_GETORIGIN													120
#define DISPID_EXLVW_GETSTRINGWIDTH											121
#define DISPID_EXLVW_GETVIEWRECTANGLE										122
#define DISPID_EXLVW_HEADERBEGINDRAG										123
#define DISPID_EXLVW_HEADERENDDRAG											124
#define DISPID_EXLVW_HEADERHITTEST											125
#define DISPID_EXLVW_HEADEROLEDRAG											126
#define DISPID_EXLVW_HEADERREFRESH											127
#define DISPID_EXLVW_HITTEST														128
#define DISPID_EXLVW_LOADSETTINGSFROMFILE								129
#define DISPID_EXLVW_OLEDRAG														130
#define DISPID_EXLVW_REDRAWITEMS												131
#define DISPID_EXLVW_REFRESH														DISPID_REFRESH
#define DISPID_EXLVW_SAVESETTINGSTOFILE									132
#define DISPID_EXLVW_SCROLL															133
#define DISPID_EXLVW_SETHEADERINSERTMARKPOSITION				134
#define DISPID_EXLVW_SETICONSPACING											135
#define DISPID_EXLVW_SETINSERTMARKPOSITION							136
#define DISPID_EXLVW_SORTGROUPS													137
#define DISPID_EXLVW_SORTITEMS													138
#define DISPID_EXLVW_GETHEADERCHEVRONRECTANGLE					154
#define DISPID_EXLVW_SETFOCUSTOHEADER										155
#define DISPID_EXLVW_GETFOOTERRECTANGLE									165
#define DISPID_EXLVW_ISFOOTERVISIBLE										166
#define DISPID_EXLVW_SHOWFOOTER													167
#define DISPID_EXLVW_FINISHOLEDRAGDROP									170


// _IExplorerListViewEvents
// methods
#define DISPID_EXLVWE_ABORTEDDRAG												1
#define DISPID_EXLVWE_AFTERSCROLL												2
#define DISPID_EXLVWE_BEFORESCROLL											3
#define DISPID_EXLVWE_BEGINCOLUMNRESIZING								4
#define DISPID_EXLVWE_BEGINMARQUEESELECTION							5
#define DISPID_EXLVWE_CACHEITEMSHINT										6
#define DISPID_EXLVWE_CARETCHANGED											DISPID_VALUE
#define DISPID_EXLVWE_CHANGEDWORKAREAS									7
#define DISPID_EXLVWE_CHANGINGWORKAREAS									8
#define DISPID_EXLVWE_CLICK															9
#define DISPID_EXLVWE_COLUMNBEGINDRAG										10
#define DISPID_EXLVWE_COLUMNENDAUTODRAGDROP							11
#define DISPID_EXLVWE_COLUMNMOUSEENTER									12
#define DISPID_EXLVWE_COLUMNMOUSELEAVE									13
#define DISPID_EXLVWE_COMPAREGROUPS											14
#define DISPID_EXLVWE_COMPAREITEMS											15
#define DISPID_EXLVWE_CONTEXTMENU												16
#define DISPID_EXLVWE_CREATEDEDITCONTROLWINDOW					17
#define DISPID_EXLVWE_CREATEDHEADERCONTROLWINDOW				18
#define DISPID_EXLVWE_CUSTOMDRAW												19
#define DISPID_EXLVWE_DBLCLICK													20
#define DISPID_EXLVWE_DESTROYEDCONTROLWINDOW						21
#define DISPID_EXLVWE_DESTROYEDEDITCONTROLWINDOW				22
#define DISPID_EXLVWE_DESTROYEDHEADERCONTROLWINDOW			23
#define DISPID_EXLVWE_DRAGMOUSEMOVE											24
#define DISPID_EXLVWE_DROP															25
#define DISPID_EXLVWE_EDITCHANGE												26
#define DISPID_EXLVWE_EDITCLICK													27
#define DISPID_EXLVWE_EDITCONTEXTMENU										28
#define DISPID_EXLVWE_EDITDBLCLICK											29
#define DISPID_EXLVWE_EDITGOTFOCUS											30
#define DISPID_EXLVWE_EDITKEYDOWN												31
#define DISPID_EXLVWE_EDITKEYPRESS											32
#define DISPID_EXLVWE_EDITKEYUP													33
#define DISPID_EXLVWE_EDITLOSTFOCUS											34
#define DISPID_EXLVWE_EDITMCLICK												35
#define DISPID_EXLVWE_EDITMDBLCLICK											36
#define DISPID_EXLVWE_EDITMOUSEDOWN											37
#define DISPID_EXLVWE_EDITMOUSEENTER										38
#define DISPID_EXLVWE_EDITMOUSEHOVER										39
#define DISPID_EXLVWE_EDITMOUSELEAVE										40
#define DISPID_EXLVWE_EDITMOUSEMOVE											41
#define DISPID_EXLVWE_EDITMOUSEUP												42
#define DISPID_EXLVWE_EDITRCLICK												43
#define DISPID_EXLVWE_EDITRDBLCLICK											44
#define DISPID_EXLVWE_ENDCOLUMNRESIZING									45
#define DISPID_EXLVWE_FILTERBUTTONCLICK									46
#define DISPID_EXLVWE_FILTERCHANGED											47
#define DISPID_EXLVWE_FINDVIRTUALITEM										48
#define DISPID_EXLVWE_FREECOLUMNDATA										49
#define DISPID_EXLVWE_FREEITEMDATA											50
#define DISPID_EXLVWE_GROUPCUSTOMDRAW										51
#define DISPID_EXLVWE_HEADERABORTEDDRAG									52
#define DISPID_EXLVWE_HEADERCLICK												53
#define DISPID_EXLVWE_HEADERCONTEXTMENU									54
#define DISPID_EXLVWE_HEADERCUSTOMDRAW									55
#define DISPID_EXLVWE_HEADERDBLCLICK										56
#define DISPID_EXLVWE_HEADERDIVIDERDBLCLICK							57
#define DISPID_EXLVWE_HEADERDRAGMOUSEMOVE								58
#define DISPID_EXLVWE_HEADERDROP												59
#define DISPID_EXLVWE_HEADERITEMGETDISPLAYINFO					60
#define DISPID_EXLVWE_HEADERMCLICK											61
#define DISPID_EXLVWE_HEADERMDBLCLICK										62
#define DISPID_EXLVWE_HEADERMOUSEDOWN										63
#define DISPID_EXLVWE_HEADERMOUSEENTER									64
#define DISPID_EXLVWE_HEADERMOUSEHOVER									65
#define DISPID_EXLVWE_HEADERMOUSELEAVE									66
#define DISPID_EXLVWE_HEADERMOUSEMOVE										67
#define DISPID_EXLVWE_HEADERMOUSEUP											68
#define DISPID_EXLVWE_HEADEROLECOMPLETEDRAG							69
#define DISPID_EXLVWE_HEADEROLEDRAGDROP									70
#define DISPID_EXLVWE_HEADEROLEDRAGENTER								71
#define DISPID_EXLVWE_HEADEROLEDRAGLEAVE								72
#define DISPID_EXLVWE_HEADEROLEDRAGMOUSEMOVE						73
#define DISPID_EXLVWE_HEADEROLEGIVEFEEDBACK							74
#define DISPID_EXLVWE_HEADEROLEQUERYCONTINUEDRAG				75
#define DISPID_EXLVWE_HEADEROLESETDATA									76
#define DISPID_EXLVWE_HEADEROLESTARTDRAG								77
#define DISPID_EXLVWE_HEADEROWNERDRAWITEM								78
#define DISPID_EXLVWE_HEADERRCLICK											79
#define DISPID_EXLVWE_HEADERRDBLCLICK										80
#define DISPID_EXLVWE_HOTITEMCHANGED										81
#define DISPID_EXLVWE_HOTITEMCHANGING										82
#define DISPID_EXLVWE_INCREMENTALSEARCHSTRINGCHANGING		83
#define DISPID_EXLVWE_INSERTEDCOLUMN										84
#define DISPID_EXLVWE_INSERTEDGROUP											85
#define DISPID_EXLVWE_INSERTEDITEM											86
#define DISPID_EXLVWE_INSERTINGCOLUMN										87
#define DISPID_EXLVWE_INSERTINGGROUP										88
#define DISPID_EXLVWE_INSERTINGITEM											89
#define DISPID_EXLVWE_ITEMACTIVATE											90
#define DISPID_EXLVWE_ITEMBEGINDRAG											91
#define DISPID_EXLVWE_ITEMBEGINRDRAG										92
#define DISPID_EXLVWE_ITEMGETDISPLAYINFO								93
#define DISPID_EXLVWE_ITEMGETINFOTIPTEXT								94
#define DISPID_EXLVWE_ITEMMOUSEENTER										95
#define DISPID_EXLVWE_ITEMMOUSELEAVE										96
#define DISPID_EXLVWE_ITEMSELECTIONCHANGED							97
#define DISPID_EXLVWE_ITEMSETTEXT												98
#define DISPID_EXLVWE_ITEMSTATEIMAGECHANGED							99
#define DISPID_EXLVWE_ITEMSTATEIMAGECHANGING						100
#define DISPID_EXLVWE_KEYDOWN														101
#define DISPID_EXLVWE_KEYPRESS													102
#define DISPID_EXLVWE_KEYUP															103
#define DISPID_EXLVWE_MCLICK														104
#define DISPID_EXLVWE_MDBLCLICK													105
#define DISPID_EXLVWE_MOUSEDOWN													106
#define DISPID_EXLVWE_MOUSEENTER												107
#define DISPID_EXLVWE_MOUSEHOVER												108
#define DISPID_EXLVWE_MOUSELEAVE												109
#define DISPID_EXLVWE_MOUSEMOVE													110
#define DISPID_EXLVWE_MOUSEUP														111
#define DISPID_EXLVWE_OLECOMPLETEDRAG										112
#define DISPID_EXLVWE_OLEDRAGDROP												113
#define DISPID_EXLVWE_OLEDRAGENTER											114
#define DISPID_EXLVWE_OLEDRAGLEAVE											115
#define DISPID_EXLVWE_OLEDRAGMOUSEMOVE									116
#define DISPID_EXLVWE_OLEGIVEFEEDBACK										117
#define DISPID_EXLVWE_OLEQUERYCONTINUEDRAG							118
#define DISPID_EXLVWE_OLESETDATA												119
#define DISPID_EXLVWE_OLESTARTDRAG											120
#define DISPID_EXLVWE_OWNERDRAWITEM											121
#define DISPID_EXLVWE_RCLICK														122
#define DISPID_EXLVWE_RDBLCLICK													123
#define DISPID_EXLVWE_RECREATEDCONTROLWINDOW						124
#define DISPID_EXLVWE_REMOVEDCOLUMN											125
#define DISPID_EXLVWE_REMOVEDGROUP											126
#define DISPID_EXLVWE_REMOVEDITEM												127
#define DISPID_EXLVWE_REMOVINGCOLUMN										128
#define DISPID_EXLVWE_REMOVINGGROUP											129
#define DISPID_EXLVWE_REMOVINGITEM											130
#define DISPID_EXLVWE_RENAMEDITEM												131
#define DISPID_EXLVWE_RENAMINGITEM											132
#define DISPID_EXLVWE_RESIZEDCONTROLWINDOW							133
#define DISPID_EXLVWE_RESIZINGCOLUMN										134
#define DISPID_EXLVWE_SELECTEDITEMRANGE									135
#define DISPID_EXLVWE_STARTINGLABELEDITING							136
#define DISPID_EXLVWE_SUBITEMMOUSEENTER									137
#define DISPID_EXLVWE_SUBITEMMOUSELEAVE									138
#define DISPID_EXLVWE_INCREMENTALSEARCHING							139
#define DISPID_EXLVWE_CHANGEDSORTORDER									140
#define DISPID_EXLVWE_CHANGINGSORTORDER									141
#define DISPID_EXLVWE_COLUMNCLICK												142
#define DISPID_EXLVWE_COLUMNDROPDOWN										143
#define DISPID_EXLVWE_COLUMNSTATEIMAGECHANGED						144
#define DISPID_EXLVWE_COLUMNSTATEIMAGECHANGING					145
#define DISPID_EXLVWE_EMPTYMARKUPTEXTLINKCLICK					146
#define DISPID_EXLVWE_GROUPASYNCHRONOUSDRAWFAILED				147
#define DISPID_EXLVWE_GROUPTASKLINKCLICK								148
#define DISPID_EXLVWE_HEADERCHEVRONCLICK								149
#define DISPID_EXLVWE_HEADERGOTFOCUS										150
#define DISPID_EXLVWE_HEADERKEYDOWN											151
#define DISPID_EXLVWE_HEADERKEYPRESS										152
#define DISPID_EXLVWE_HEADERKEYUP												153
#define DISPID_EXLVWE_HEADERLOSTFOCUS										154
#define DISPID_EXLVWE_HEADEROLEDRAGENTERPOTENTIALTARGET	155
#define DISPID_EXLVWE_HEADEROLEDRAGLEAVEPOTENTIALTARGET	156
#define DISPID_EXLVWE_HEADEROLERECEIVEDNEWDATA					157
#define DISPID_EXLVWE_ITEMASYNCHRONOUSDRAWFAILED				158
#define DISPID_EXLVWE_OLEDRAGENTERPOTENTIALTARGET				159
#define DISPID_EXLVWE_OLEDRAGLEAVEPOTENTIALTARGET				160
#define DISPID_EXLVWE_OLERECEIVEDNEWDATA								161
#define DISPID_EXLVWE_FOOTERITEMCLICK										162
#define DISPID_EXLVWE_FREEFOOTERITEMDATA								163
#define DISPID_EXLVWE_ITEMGETGROUP    									164
#define DISPID_EXLVWE_ITEMGETOCCURRENCESCOUNT						165
#define DISPID_EXLVWE_MAPGROUPWIDETOTOTALITEMINDEX			166
#define DISPID_EXLVWE_SETTINGITEMINFOTIPTEXT						167
#define DISPID_EXLVWE_COLLAPSEDGROUP										168
#define DISPID_EXLVWE_EXPANDEDGROUP											169
#define DISPID_EXLVWE_GROUPGOTFOCUS											170
#define DISPID_EXLVWE_GROUPLOSTFOCUS										171
#define DISPID_EXLVWE_GROUPSELECTIONCHANGED							172
#define DISPID_EXLVWE_CANCELSUBITEMEDIT									173
#define DISPID_EXLVWE_CONFIGURESUBITEMCONTROL						174
#define DISPID_EXLVWE_ENDSUBITEMEDIT										175
#define DISPID_EXLVWE_GETSUBITEMCONTROL									176
#define DISPID_EXLVWE_INVOKEVERBFROMSUBITEMCONTROL			177
#define DISPID_EXLVWE_EDITMOUSEWHEEL										178
#define DISPID_EXLVWE_EDITXCLICK												179
#define DISPID_EXLVWE_EDITXDBLCLICK											180
#define DISPID_EXLVWE_HEADERMOUSEWHEEL									181
#define DISPID_EXLVWE_HEADERXCLICK											182
#define DISPID_EXLVWE_HEADERXDBLCLICK										183
#define DISPID_EXLVWE_MOUSEWHEEL												184
#define DISPID_EXLVWE_XCLICK														185
#define DISPID_EXLVWE_XDBLCLICK													186


// IListViewColumn
// properties
#define DISPID_LVC_ALIGNMENT														1
#define DISPID_LVC_BITMAPHANDLE													2
#define DISPID_LVC_CAPTION															DISPID_VALUE
#define DISPID_LVC_COLUMNDATA														3
#define DISPID_LVC_FILTER																4
#define DISPID_LVC_HEIGHT																5
#define DISPID_LVC_ICONINDEX														6
#define DISPID_LVC_IMAGEONRIGHT													7
#define DISPID_LVC_INDEX																8
#define DISPID_LVC_LEFT																	9
#define DISPID_LVC_OWNERDRAWN														10
#define DISPID_LVC_POSITION															11
#define DISPID_LVC_SELECTED															12
#define DISPID_LVC_SORTARROW														13
#define DISPID_LVC_TOP																	14
#define DISPID_LVC_WIDTH																15
#define DISPID_LVC_CARET																18
#define DISPID_LVC_DEFAULTWIDTH													19
#define DISPID_LVC_ID																		20
#define DISPID_LVC_IDEALWIDTH														21
#define DISPID_LVC_MINIMUMWIDTH													22
#define DISPID_LVC_RESIZABLE														23
#define DISPID_LVC_SHOWDROPDOWNBUTTON										24
#define DISPID_LVC_STATEIMAGEINDEX											25
#ifdef INCLUDESHELLBROWSERINTERFACE
	#define DISPID_LVC_SHELLLISTVIEWCOLUMNOBJECT						27
#endif
#define DISPID_LVC_LOCALE																28
#define DISPID_LVC_TEXTPARSINGFLAGS											29
// methods
#define DISPID_LVC_CREATEDRAGIMAGE											16
#define DISPID_LVC_STARTFILTEREDITING										17
#define DISPID_LVC_GETDROPDOWNRECTANGLE									26


// IListViewColumns
// properties
#define DISPID_LVCS_ITEM																DISPID_VALUE
#define DISPID_LVCS__NEWENUM														DISPID_NEWENUM
#define DISPID_LVCS_POSITIONS														1
#define DISPID_LVCS_POSITIONSSTRING											7
// methods
#define DISPID_LVCS_ADD																	2
#define DISPID_LVCS_CLEARALLFILTERS											3
#define DISPID_LVCS_COUNT																4
#define DISPID_LVCS_REMOVE															5
#define DISPID_LVCS_REMOVEALL														6


// IVirtualListViewColumn
// properties
#define DISPID_VLVC_ALIGNMENT														1
#define DISPID_VLVC_BITMAPHANDLE												2
#define DISPID_VLVC_CAPTION															DISPID_VALUE
#define DISPID_VLVC_COLUMNDATA													3
#define DISPID_VLVC_FILTER															4
#define DISPID_VLVC_ICONINDEX														5
#define DISPID_VLVC_IMAGEONRIGHT												6
#define DISPID_VLVC_OWNERDRAWN													7
#define DISPID_VLVC_POSITION														8
#define DISPID_VLVC_SORTARROW														9
#define DISPID_VLVC_WIDTH																10
#define DISPID_VLVC_CARET																11
#define DISPID_VLVC_DEFAULTWIDTH												12
#define DISPID_VLVC_MINIMUMWIDTH												13
#define DISPID_VLVC_RESIZABLE														14
#define DISPID_VLVC_SHOWDROPDOWNBUTTON									15
#define DISPID_VLVC_STATEIMAGEINDEX											16
// methods


// IListViewItem
// properties
#define DISPID_LVI_ACTIVATING														1
#define DISPID_LVI_ANCHOR																2
#define DISPID_LVI_CARET																3
#define DISPID_LVI_DROPHILITED													4
#define DISPID_LVI_GHOSTED															5
#define DISPID_LVI_GLOWING															6
#define DISPID_LVI_GROUP																7
#define DISPID_LVI_GROUPINDEX														8
#define DISPID_LVI_HOT																	9
#define DISPID_LVI_ICONINDEX														10
#define DISPID_LVI_ID																		11
#define DISPID_LVI_INDENT																12
#define DISPID_LVI_INDEX																13
#define DISPID_LVI_ITEMDATA															14
#define DISPID_LVI_OVERLAYINDEX													15
#define DISPID_LVI_SELECTED															16
#ifdef INCLUDESHELLBROWSERINTERFACE
	#define DISPID_LVI_SHELLLISTVIEWITEMOBJECT							17
#endif
#define DISPID_LVI_STATEIMAGEINDEX											18
#define DISPID_LVI_SUBITEMS															19
#define DISPID_LVI_TEXT																	DISPID_VALUE
#define DISPID_LVI_TILEVIEWCOLUMNS											20
#define DISPID_LVI_WORKAREA															21
// methods
#define DISPID_LVI_CREATEDRAGIMAGE											22
#define DISPID_LVI_ENSUREVISIBLE												23
#define DISPID_LVI_FINDNEXTITEM													24
#define DISPID_LVI_ISVISIBLE														25
#define DISPID_LVI_GETPOSITION													26
#define DISPID_LVI_GETRECTANGLE													27
#define DISPID_LVI_SETPOSITION													28
#define DISPID_LVI_STARTLABELEDITING										29
#define DISPID_LVI_UPDATE																30
#define DISPID_LVI_SETINFOTIPTEXT												31


// IListViewItems
// properties
#define DISPID_LVIS_CASESENSITIVEFILTERS								1
#define DISPID_LVIS_COMPARISONFUNCTION									2
#define DISPID_LVIS_FILTER															3
#define DISPID_LVIS_FILTERTYPE													4
#define DISPID_LVIS_ITEM																DISPID_VALUE
#define DISPID_LVIS__NEWENUM														DISPID_NEWENUM
// methods
#define DISPID_LVIS_ADD																	5
#define DISPID_LVIS_CONTAINS														6
#define DISPID_LVIS_COUNT																7
#define DISPID_LVIS_REMOVE															8
#define DISPID_LVIS_REMOVEALL														9


// IListViewItemContainer
// properties
#define DISPID_LVIC_ITEM																DISPID_VALUE
#define DISPID_LVIC__NEWENUM														DISPID_NEWENUM
// methods
#define DISPID_LVIC_ADD																	1
#define DISPID_LVIC_CLONE																2
#define DISPID_LVIC_COUNT																3
#define DISPID_LVIC_CREATEDRAGIMAGE											4
#define DISPID_LVIC_REMOVE															5
#define DISPID_LVIC_REMOVEALL														6


// IVirtualListViewItem
// properties
#define DISPID_VLVI_ACTIVATING													1
#define DISPID_VLVI_CARET																2
#define DISPID_VLVI_DROPHILITED													3
#define DISPID_VLVI_GHOSTED															4
#define DISPID_VLVI_GLOWING															5
#define DISPID_VLVI_GROUP																6
#define DISPID_VLVI_ICONINDEX														7
#define DISPID_VLVI_INDENT															8
#define DISPID_VLVI_INDEX																9
#define DISPID_VLVI_ITEMDATA														10
#define DISPID_VLVI_OVERLAYINDEX												11
#define DISPID_VLVI_SELECTED														12
#define DISPID_VLVI_STATEIMAGEINDEX											13
#define DISPID_VLVI_TEXT																DISPID_VALUE
#define DISPID_VLVI_TILEVIEWCOLUMNS											14
// methods


// IListViewSubItem
// properties
#define DISPID_LVSI_ACTIVATING													1
#define DISPID_LVSI_GHOSTED															2
#define DISPID_LVSI_GLOWING															3
#define DISPID_LVSI_ICONINDEX														4
#define DISPID_LVSI_INDEX																5
#define DISPID_LVSI_OVERLAYINDEX												6
#define DISPID_LVSI_PARENTITEM													7
#define DISPID_LVSI_STATEIMAGEINDEX											8
#define DISPID_LVSI_TEXT																DISPID_VALUE
// methods
#define DISPID_LVSI_GETRECTANGLE												9


// IListViewSubItems
// properties
#define DISPID_LVSIS_ITEM																DISPID_VALUE
#define DISPID_LVSIS__NEWENUM														DISPID_NEWENUM
#define DISPID_LVSIS_PARENTITEM													1
// methods
#define DISPID_LVSIS_COUNT															2


// IListViewFooterItem
// properties
#define DISPID_LVFI_CARET																1
#define DISPID_LVFI_INDEX																2
#define DISPID_LVFI_ITEMDATA														3
#define DISPID_LVFI_TEXT																DISPID_VALUE
// methods
#define DISPID_LVFI_GETRECTANGLE												4


// IListViewFooterItems
// properties
#define DISPID_LVFIS_ITEM																DISPID_VALUE
#define DISPID_LVFIS__NEWENUM														DISPID_NEWENUM
// methods
#define DISPID_LVFIS_ADD																1
//#define DISPID_LVFIS_CONTAINS														2
#define DISPID_LVFIS_COUNT															3
//#define DISPID_LVFIS_REMOVE															4
#define DISPID_LVFIS_REMOVEALL													5


// IListViewGroup
// properties
#define DISPID_LVG_ALIGNMENT														1
#define DISPID_LVG_COLLAPSED														2
#define DISPID_LVG_ID																		4
#define DISPID_LVG_LISTITEMS														5
#define DISPID_LVG_POSITION															6
#define DISPID_LVG_TEXT																	DISPID_VALUE
#define DISPID_LVG_CARET																7
#define DISPID_LVG_COLLAPSIBLE													8
#define DISPID_LVG_DESCRIPTIONTEXTBOTTOM								9
#define DISPID_LVG_DESCRIPTIONTEXTTOP										10
#define DISPID_LVG_ICONINDEX														11
#define DISPID_LVG_INDEX																12
#define DISPID_LVG_SELECTED															13
#define DISPID_LVG_SHOWHEADER														14
#define DISPID_LVG_SUBTITLETEXT													15
#define DISPID_LVG_TASKTEXT															16
#define DISPID_LVG_FIRSTITEM														18
#define DISPID_LVG_ITEMCOUNT														19
#define DISPID_LVG_SUBSETED															20
#define DISPID_LVG_SUBSETLINKFOCUSED										21
#define DISPID_LVG_SUBSETLINKTEXT												22
// methods
#define DISPID_LVG_GETRECTANGLE													17


// IListViewGroups
// properties
#define DISPID_LVGS_ITEM																DISPID_VALUE
#define DISPID_LVGS__NEWENUM														DISPID_NEWENUM
// methods
#define DISPID_LVGS_ADD																	1
#define DISPID_LVGS_COUNT																2
#define DISPID_LVGS_REMOVE															3
#define DISPID_LVGS_REMOVEALL														4
#define DISPID_LVGS_CONTAINS														5


// IVirtualListViewGroup
// properties
#define DISPID_VLVG_ALIGNMENT														1
#define DISPID_VLVG_COLLAPSED														2
#define DISPID_VLVG_ID																	4
#define DISPID_VLVG_TEXT																DISPID_VALUE
#define DISPID_VLVG_CARET																5
#define DISPID_VLVG_COLLAPSIBLE													6
#define DISPID_VLVG_DESCRIPTIONTEXTBOTTOM								7
#define DISPID_VLVG_DESCRIPTIONTEXTTOP									8
#define DISPID_VLVG_ICONINDEX														9
#define DISPID_VLVG_SELECTED														10
#define DISPID_VLVG_SHOWHEADER													11
#define DISPID_VLVG_SUBTITLETEXT												12
#define DISPID_VLVG_TASKTEXT														13
#define DISPID_VLVG_SUBSETED														14
#define DISPID_VLVG_SUBSETLINKFOCUSED										15
#define DISPID_VLVG_SUBSETLINKTEXT											16
// methods


// IListViewWorkArea
// properties
#define DISPID_LVWA_INDEX																DISPID_VALUE
#define DISPID_LVWA_LISTITEMS														1
// methods
#define DISPID_LVWA_GETRECTANGLE												2
#define DISPID_LVWA_SETRECTANGLE												3


// IListViewWorkAreas
// properties
#define DISPID_LVWAS_ITEM																DISPID_VALUE
#define DISPID_LVWAS__NEWENUM														DISPID_NEWENUM
// methods
#define DISPID_LVWAS_ADD																1
#define DISPID_LVWAS_COUNT															2
#define DISPID_LVWAS_REMOVE															3
#define DISPID_LVWAS_REMOVEALL													4


// IVirtualListViewWorkArea
// properties
#define DISPID_VLVWA_INDEX															DISPID_VALUE
// methods
#define DISPID_VLVWA_GETRECTANGLE												1


// IVirtualListViewWorkAreas
// properties
#define DISPID_VLVWAS_ITEM															DISPID_VALUE
#define DISPID_VLVWAS__NEWENUM													DISPID_NEWENUM
// methods
#define DISPID_VLVWAS_COUNT															1


// IOLEDataObject
// properties
// methods
#define DISPID_ODO_CLEAR																1
#define DISPID_ODO_GETCANONICALFORMAT										2
#define DISPID_ODO_GETDATA															3
#define DISPID_ODO_GETFORMAT														4
#define DISPID_ODO_SETDATA															5
#define DISPID_ODO_GETDROPDESCRIPTION										6
#define DISPID_ODO_SETDROPDESCRIPTION										7
